version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./:/usr/src/hos-serive
      - /usr/src/hos-serive/node_modules
    ports:
      - "1082:1082"