FROM node:18.20.6
LABEL maintainer="jana.ru.sidorova@yandex.ru"
ENV NODE_ENV=development PORT=1082

WORKDIR /usr/src/hos-service

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

COPY . .

EXPOSE 1082
CMD ["./node_modules/.bin/nodemon", "index.js"]
