version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./:/usr/src/hos-service
      - /usr/src/hos-service/node_modules
    ports:
      - "1082:1082"
    links:
      - mongo-db
    env_file:
     - .env

  mongo-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
    command: mongod --quiet --logpath /dev/null 
