openapi: 3.0.0
info:
  title: API
  version: 1.0.0
servers:
  - url: 'http://localhost:1082/'
    description: Development
  - url: 'https://hos-service.dogcatbmpz.by/'
    description: Production
tags:
  - name: Notices
    description: CRUD for notices
  - name: Claims
    description: CRUD for claims
  - name: Users
    description: User additional information
paths:
  /notices:
    post:
      summary: Create new notice
      tags:
        - Notices
      security:
        - AccessTokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                internalOnly:
                  type: boolean
                animal_id:
                  type: string
      responses:
        '201':
          description: Notice created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Notice'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get ID's of existing notices
      tags:
        - Notices
      responses:
        '200':
          description: Returns existing notices
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: string
  '/notices/{noticeId}':
    parameters:
      - name: noticeId
        in: path
        description: ID of notice
        required: true
        schema:
          type: string
    get:
      summary: Get existing notice by ID
      tags:
        - Notices
      responses:
        '200':
          description: Returns requested notice
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Notice'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Edit existing notice
      tags:
        - Notices
      security:
        - AccessTokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                internalOnly:
                  type: boolean
                animal_id:
                  type: string
      responses:
        '200':
          description: Returns edited notice
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Notice'
        '400':
          description: Validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete existing notice
      tags:
        - Notices
      security:
        - AccessTokenAuth: []
      responses:
        '204':
          description: Notice successfully deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /claims:
    get:
      summary: Get claims
      tags:
        - Claims
      parameters:
        - name: from
          in: query
          description: date from which to return
          required: false
          schema:
            type: string
        - name: to
          in: query
          description: date from which to return
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Returns claims filtered by from & to parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        user_id:
                          type: string
                          format: uuid
                        date:
                          type: string
                          format: date-time
                        type:
                          type: string
                          enum:
                            - morning
                            - evening
                        arrival_time:
                          type: string
                        additional_people:
                          type: integer
                        comment:
                          type: string
                        questionable:
                          type: boolean
                        guest_id:
                          type: string
                          format: uuid
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                              format: uuid
                            name:
                              type: string
                            surname:
                              type: string
                            phone:
                              type: string
                            email:
                              type: string
                            birthday:
                              type: string
                              format: date-time
                        guest:
                          type: object
                          properties:
                            id:
                              type: string
                              format: uuid
                            name:
                              type: string
                            surname:
                              type: string
                            phone:
                              type: string
        '400':
          description: Fails when from or to parameters are invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    post:
      summary: Create new claim
      tags:
        - Claims
      security:
        - AccessTokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  format: uuid
                date:
                  type: string
                  format: date-time
                type:
                  type: string
                  enum:
                    - morning
                    - evening
                arrival_time:
                  type: string
                additional_people:
                  type: integer
                comment:
                  type: string
                questionable:
                  type: boolean
                guest:
                  type: object
                  properties:
                    name:
                      type: string
                    surname:
                      type: string
                    phone:
                      type: string
              required:
                - user_id
                - date
                - type
      responses:
        '200':
          description: Returns new claim
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Claim'
        '400':
          description: Fails with validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 'Fails with not enough permissions, not yours'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/claims/{claimId}':
    parameters:
      - name: claimId
        in: path
        description: ID of claim
        required: true
        schema:
          type: string
    patch:
      summary: Edit existing claim
      tags:
        - Claims
      security:
        - AccessTokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                arrival_time:
                  type: string
                additional_people:
                  type: integer
                comment:
                  type: string
                questionable:
                  type: boolean
      responses:
        '200':
          description: Returns edited claim
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Claim'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden when updating not yours
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete existing claim
      tags:
        - Claims
      security:
        - AccessTokenAuth: []
      responses:
        '204':
          description: Claim successfully deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/users/{userId}/claims':
    get:
      summary: Get claims for one user
      tags:
        - Users
      security:
        - AccessTokenAuth: []
      parameters:
        - name: userId
          in: path
          description: user id which claims to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns claims for one user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Claim'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /claims/rating:
    get:
      summary: Get claims rating
      tags:
        - Claims
      security:
        - AccessTokenAuth: []
      responses:
        '200':
          description: 'Returns claims rating for last month, last year and all time'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      allTime:
                        type: array
                        items:
                          $ref: '#/components/schemas/ClaimRating'
                      year:
                        type: array
                        items:
                          $ref: '#/components/schemas/ClaimRating'
                      month:
                        type: array
                        items:
                          $ref: '#/components/schemas/ClaimRating'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden when do not have permission to view rating
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    AccessTokenAuth:
      type: apiKey
      in: header
      name: x-access-token
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          default: false
        error:
          type: string
    ValidationError:
      type: object
      properties:
        success:
          type: boolean
          default: false
        errors:
          type: array
          items:
            type: object
            properties:
              value:
                type: string
              msg:
                type: string
              param:
                type: string
              location:
                type: string
    Notice:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        description:
          type: string
        internalOnly:
          type: boolean
        animal_id:
          type: string
    Claim:
      type: object
      properties:
        _id:
          type: string
        user_id:
          type: string
          format: uuid
        date:
          type: string
          format: date-time
        type:
          type: string
          enum:
            - morning
            - evening
        arrival_time:
          type: string
        additional_people:
          type: integer
        comment:
          type: string
        questionable:
          type: boolean
        guest_id:
          type: string
          format: uuid
    ClaimRating:
      type: object
      properties:
        id:
          type: string
          format: uuid
        fullName:
          type: string
        claimsCount:
          type: number
