openapi: 3.0.0
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:1082/
    description: Development
  - url: https://hos-service.dogcatbmpz.by/
    description: Production
tags:
  - name: Notices
    description: CRUD for notices
  - name: Claims
    description: CRUD for claims
  - name: Users
    description: User additional information
paths:
  /notices:
    $ref: "./paths/notices.yaml"
  /notices/{noticeId}:
    $ref: "./paths/notice.yaml"
  /claims:
    $ref: "./paths/claims.yaml"
  /claims/{claimId}:
    $ref: "./paths/claim.yaml"
  /users/{userId}/claims:
    $ref: "./paths/user-claims.yaml"
components:
  securitySchemes:
    AccessTokenAuth:
      type: apiKey
      in: header
      name: x-access-token
  schemas:
    $ref: "./schemas/index.yaml"
