name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, development ]
  workflow_dispatch:
  
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.0', '4.4']
        
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: admin
          mongodb-password: admin
          mongodb-db: test-db
      - name: Install dependencies
        run: |
          npm install
          npm ci 
      - name: test
        run: npm run test
        env:
          MONGO_HOSTNAME: localhost
          MONGO_PORT: 27017
          MONGODB_USERNAME: admin
          MONGODB_PASSWORD: admin
          MONGODB_DATABASE: test-db
          EVENT_KEY: event-key
          DOCKER_AUTH_SERVICE_URL: http://example.com